# Generated by Django 3.2 on 2023-01-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210709_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '01. Banners'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '03. Brand'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '08. Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '09. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '02. Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '04. Colors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '06. Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '07. ProductAttributes'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '12.Reviews'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '05. Sizes'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': '10.AddressBook'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '11.Wishlist'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('In Transit', 'In Transit'), ('delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
